### PR TITLE
[travis] Fix .travis.yml syntax bug

### PR DESCRIPTION
**Pull request by wei**
[image](https://travis-ci.org/super-inspire/super-inspire-end/builds/486802198#L1459)
https://travis-ci.org/super-inspire/super-inspire-end/builds/486802198#L1459

### CODE REVIEW

**Comment by import-yuefeng** [comment]
抱歉, 之前春节有点忙, 积压了好多task, 我看一下~

**Comment by wei** [comment]
Secret 环境变量不提供给 pull request build 哈 直接在 master 测试吧

**Comment by import-yuefeng** [comment]
> Secret 环境变量不提供给 pull request builds 哈 直接在 master 测试吧
> 
> Encrypted environment variables have been removed for security reasons.
> See https://docs.travis-ci.com/user/pull-requests/#pull-requests-and-security-restrictions

感谢提醒🤣, 我还一直说这个环境变量怎么回事, 然后网络又差, 搞了挺久的🤣

**Comment by import-yuefeng** [comment]
fix .travis.yml syntax bug.

**Comment by wei** [comment]
成功啦 🙂

**Comment by import-yuefeng** [comment]
> 成功啦 🙂

是哒, 已经完成[服务器更新](35.220.214.188:8888), 非常感谢帮助!~

**Pull request merged**
